name: content_reader_flutter
description: A Flutter RSS Reader app with offline support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  webfeed_plus: ^1.0.0
  http: ^1.1.0
  html: ^0.15.3
  intl: ^0.18.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
